### ISSUE TITLE
idle in transaction

### ISSUE THREAD

**Issue by saily** [zodb/relstorage#11] opened 2014-03-25 12:37 UTC
Why are all connections left in state ``idle in transaction``? is this a general requirement to support zodb/zope or would it be possible to release that transaction?

**Comment by do3cc** [comment] 2015-12-01 17:55
https://mail.zope.org/pipermail/zodb-dev/2014-March/015198.html

**Comment by do3cc** [comment] 2015-12-01 17:55
Duplicate of #7

**Comment by mauritsvanrees** [comment] 2015-12-03 16:21
Also, if you are using RelStorage 1.5.0 or older, this might be a problem that was fixed in 1.5.1 (November 2011). From the changelog: "RelStorage was opening a test database connection (and was leaving it idle in a transaction with recent ZODB versions that support IMVCCStorage.) RelStorage no longer opens that test connection."

**Comment by do3cc** [comment] 2015-12-03 16:34
No, it is related to this:
https://github.com/zodb/relstorage/blob/9dacfa56c5fc0ae6db5e803ad5ebbf0f6b346448/relstorage/storage.py#L1221
The polling interval

**Comment by hathawsh** [comment] 2015-12-05 20:15
The poll interval option is off by default. Don't turn it on if this is a concern for you. Actually, perhaps the option should be removed altogether.

**Closed by hathawsh** 2015-12-05 20:15 UTC

**Comment by jensens** [comment] 2015-12-05 20:26
So I need to check why some of my 1.6.0b3 instances with no poll interval set (defaults active) are resulting in idle in transaction on PGSQL.

**Comment by do3cc** [comment] 2015-12-05 21:33
I also tried it yesterday, with 1.5.1. Poll Intervall 0, still immed. Idle transactions.



Sent from my iPhone because UPC sucks

On 05 Dec 2015, at 21:26, Jens W. Klein <notifications@github.com<mailto:notifications@github.com>> wrote:


So I need to check why some of my 1.6.0b3 instances with no poll interval set (defaults active) are resulting in idle in transaction on PGSQL.

-
Reply to this email directly or view it on GitHub<https://github.com/zodb/relstorage/issues/11#issuecomment-162243403>.

________________________________________________________ The contents of this e-mail and any attachments are confidential to the intended recipient. They may not be disclosed to or used by or copied in any way by anyone other than the intended recipient. If this e-mail is received in error, please immediately notify the sender and delete the e-mail and attached documents. Please note that neither the sender nor the sender's company accept any responsibility for viruses and it is your responsibility to scan or otherwise check this e-mail and any attachments.

**Comment by do3cc** [comment] 2016-10-10 13:02
Postgres 9.6 has a new option , idle transaction timeout. This blogpost https://www.credativ.de/blog/postgresql-96-feature-idle-transaction-timeout (german) also explains the downsides of having idle transactions open. We are currently in maintenance mode with our big system using Relstorage. @jensens, are you actively working on some psql site where you can test this option to see if it makes a difference?

**Comment by jamadden** [comment] 2016-10-10 13:16
FWIW, the poll interval option has been removed in RelStorage 2.0.
