### ISSUE TITLE
Blobs are not removed after zodbpack

### ISSUE THREAD

**Issue by esoth** [zodb/relstorage#24] opened 2015-07-13 15:11 UTC
1. Starting size of blobstorage directory: 119M
2. Add a ~1GB file to portal. blobstorage size: ~1.3GB
3. Delete file from zope and run zodbpack
4. Postgres db size is fine, but blobstorage directory remains ~1.3GB

Perhaps I'm missing something but my understanding was that packing was supposed to remove blobs on the file system that no longer have any references pointed to them.

buildout.cfg snippet:
> rel-storage =
>    keep-history false
>    type postgresql
>    blob-dir /sprj/btp_zope_plone4/blobstorage/maize
>    dsn dbname='${databases:zodb}' user='${users:zodb}' host='${hosts:zodb}' password='${passwords:zodb}' port='${ports:zodb}'

zpack.cfg snippet:
> &lt;relstorage&gt;
>  pack-gc true
>  &lt;postgresql&gt;
>    dsn dbname='xxx' user='xxx' host='xxx' password='xxx' port='xxx'
>  &lt;/postgresql&gt;
>  keep-history false
> &lt;/relstorage&gt;

I did find this issue https://github.com/zopefoundation/ZEO/issues/2 but my understanding is that this is not analogous to RelStorage because with shared-blob-dir = true (default for RelStorage) here there is no blobcache and setting a blob cache size value would be ignored. How do prevent the blobstorage dir from growing indefinitely?

Tested with 1.6.0b3 and 1.5.0.

**Comment by esoth** [comment] 2015-07-17 15:59
I dug through some code and believe I see my issue. The blob-dir also needs to be defined in zpack.cfg because the zodbpack script is completely unaware of any relstorage settings used by the buildout's plone/zope process. It seems a little silly to have to duplicate this, but it makes sense.

Also it looks like when a database object is deleted during a pack it checks if a blobhelper instance is defined - which it won't be if blob-dir wasn't provided. If it is, it finds the filesystem directory of the blob and deletes it. If not, it does nothing. Since the db object is deleted in this step the filesystem blob will be orphaned indefinitely, even if zpack.cfg is corrected to provide a blob-dir value in the future.

What I will try to do next is see if I can use zodbconvert to move to a new blob-dir, delete the old dir and its orphans, and then convert back to the original dir.

**Comment by hathawsh** [comment] 2015-12-05 20:22
Did your solution work, @esoth?

**Comment by jamadden** [comment] 2016-06-15 11:15
Closing this because it's been a year since last contact, and last contact seemed to show a resolution. Please feel free to reopen if the issue is not resolved.

**Closed by jamadden** 2016-06-15 11:15 UTC
Labels: question
